### ISSUE TITLE
[BUG] Module conflict: MagiskHidePropsConf module and EdXposed module can not be used at the same time. If one module is disabled, another module can be used. The attached file is the log of MagiskHidePropsConf.

### ISSUE THREAD

**Issue by 2220209876** [Magisk-Modules-Repo/MagiskHidePropsConf#18] opened 2019-03-02 15:29 UTC
**What happened?**
Module conflict: MagiskHidePropsConf module and EdXposed module can not be used at the same time. If one module is disabled, another module can be used. The attached file is the log of MagiskHidePropsConf.

MagiskHidePropsConf： https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf
EdXposed ： https://github.com/ElderDrivers/EdXposed

————————————————————————————————————————————
模块冲突：MagiskHidePropsConf模块与EdXposed模块同时启用两者都不能使用，如果禁用一个模块另一个模块可以使用，附件里是MagiskHidePropsConf的日志。

[propslogs 2019-03-02 23-27-05.zip](https://github.com/ElderDrivers/EdXposed/files/2922231/propslogs.2019-03-02.23-27-05.zip)

[
![2019-03-02_23-21-58](https://user-images.githubusercontent.com/7346652/53684030-369ef100-3d43-11e9-82c2-235563c280e3.png)
](url)

**Comment by Didgeridoohan** [comment] 2019-03-02 16:29
The only issue I can see from the logs is that the service.sh script doesn't run. Unfortunately the Magisk log ends with a crash (likely related).

Could you test with only those two modules installed, to make sure there are no synergies with other modules. And, if you could place this script in /data/adb/post-fd-data.d (you can remove the .txt extension), give it execution permission, reboot and then post the /cache/bootlog.log file that is created, that might show more.

[bootlog.txt](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2922282/bootlog.txt)

**Comment by 2220209876** [comment] 2019-03-03 03:21
> 我从日志中看到的唯一问题是service.sh脚本无法运行。不幸的是，Magisk日志以崩溃结束（可能相关）。
> 
> 您是否可以仅安装这两个模块进行测试，以确保与其他模块没有协同作用。并且，如果您可以将此脚本放在/data/adb/post-fd-data.d（您可以删除.txt扩展名），为其授予执行权限，重新启动，然后发布/cache/bootlog.log文件，即创建，可能会显示更多。
> 
> [BOOTLOG.TXT](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2922282/bootlog.txt)

/data/adb/post-fd-data.d/BOOTLOG
Is the script path placed like this?

**Comment by Didgeridoohan** [comment] 2019-03-03 04:43
Yes

**Comment by 2220209876** [comment] 2019-03-03 05:58
> 是

![2019-03-03_13-24-19](https://user-images.githubusercontent.com/7346652/53691421-95528200-3db8-11e9-8358-cfdebe715248.png)
[propslogs1-4 2019-03-03 13-54-01.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2922805/propslogs1-4.2019-03-03.13-54-01.zip)
Logs 1, 2 are when the BOOTLOG file is not added
Logs 3 and 4 are generated after the BOOTLOG file is added.

riru-core-v15 ： https://github.com/RikkaApps/Riru/releases

The magisk-riru-core-v15 module is the core of edxposed so there is no deactivation

MagiskHidePropsConf requires busybox so it is not deactivated

**Comment by Didgeridoohan** [comment] 2019-03-03 07:25
Ok... But you didn't include the actual bootlog.log file that is generated by the bootlog script. You'll find it in /cache.

**Comment by 2220209876** [comment] 2019-03-03 08:21
> 好的...但是你没有包含bootlog脚本生成的实际bootlog.log文件。你会在/ cache中找到它。


Sorry, I forgot, I don’t know if the log has any effect, because I have restarted the phone many times.
[log.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2922892/log.zip)

**Comment by Didgeridoohan** [comment] 2019-03-03 09:38
Hard to say what it could be. There are tons of errors in there and you have so many mounts and links from your Magisk modules that it takes almost a second and a half to get it all set up (I've got a pretty huge amount of mounts and links on my setup as well, but it takes less than a tenth of a second to complete).

I'm strongly suspecting that it's caused by EdXposed (it is pretty experimental after all), but if you're up to it I could take a look at one other thing. If you could, please provide the Magisk debug logs from a boot where you have disabled EdXposed and one where you've disabled MagiskHide Props Config. I'd like to compare...

**Comment by 2220209876** [comment] 2019-03-03 15:44
Sorry, I don't know how to operate. If you can, try to install EDxposed on your side? (This is also convenient for extracting logs)

**Comment by Didgeridoohan** [comment] 2019-03-03 17:39
The Magisk debug log is just the regular Magisk log, but when you have the Canary Debug Build installed. From your previous posts it looks like you have that already, so it's just a matter of disabling/enabling the modules reboot and save the log.

**Comment by Didgeridoohan** [comment] 2019-03-03 17:40
And I'm unlikely to start messing around with EdXposed... Don't have any devices where I would want to experiment with that.

**Comment by 2220209876** [comment] 2019-03-04 02:09
> Magisk调试日志只是常规的Magisk日志，但是当您安装了Canary Debug Build时。从您之前的帖子看起来您已经拥有它，所以这只是禁用/启用模块重启并保存日志的问题。

Need to change back to the official version of magisk? Don't need Canary Debug Build?

**Comment by 2220209876** [comment] 2019-03-04 03:46
Can you tell the telegram account if you can? Feel that instant chat is more convenient to communicate

**Comment by Didgeridoohan** [comment] 2019-03-04 04:22
Sorry, don't really use Telegram... And I think I'm explaining poorly. Let me list things more clearly:

With the Magisk Canary debug build installed, do the following:

1. Disable EdXposed.
2. Reboot.
3. Save the logs.
4. Enable EdXposed.
5. Disable MagiskHide Props Config.
6. Reboot.
7. Save the logs.

**Comment by 2220209876** [comment] 2019-03-04 06:51
[201903041338.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2924612/201903041338.zip)
Disable EdXposed.
——————————————————
[201903041345.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2924614/201903041345.zip)
Disable MagiskHide Props Config.（Forced a reboot during the extraction of the log）
——————————————————
[201903041350.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/2924615/201903041350.zip)
Enable EdXposed and Enable  MagiskHide Props Config.

**Comment by Didgeridoohan** [comment] 2019-03-04 11:54
Looking at those logs I'm going to conclude that the issue very likely is being caused by EdXposed. Whatever it's doing is putting such a strain on the system at boot that Magisk doesn't have time to finish everything. It's possible that it's some kind of combination, but the ground cause is probably EdXposed.

I'm not gonna be digging any deeper into this, since I have neither the time, nor the means, but if you figure out anything more and find that there's something about my module that can be fixed, please open a new issue. For now, I'm closing this with the motivation: "not my fault".

**Closed by Didgeridoohan** 2019-03-04 11:54 UTC

**Comment by 2220209876** [comment] 2019-03-04 12:34
Okay thank you

**Comment by 2220209876** [comment] 2019-03-22 12:51
> Looking at those logs I'm going to conclude that the issue very likely is being caused by EdXposed. Whatever it's doing is putting such a strain on the system at boot that Magisk doesn't have time to finish everything. It's possible that it's some kind of combination, but the ground cause is probably EdXposed.
> 
> I'm not gonna be digging any deeper into this, since I have neither the time, nor the means, but if you figure out anything more and find that there's something about my module that can be fixed, please open a new issue. For now, I'm closing this with the motivation: "not my fault".

@Didgeridoohan 

Later, it was found that although the settings page could not be accessed in the terminal, fingerprints would be effective if they had been set before.

**Comment by Didgeridoohan** [comment] 2019-03-22 13:16
Yes, that is expected... The props script is completely separate from the actual settings of the prop values. You don't even need to use the props script if you instead use the configuration file.

**Comment by 2220209876** [comment] 2019-03-22 13:26
> Yes, that is expected... The props script is completely separate from the actual settings of the prop values. You don't even need to use the props script if you instead use the configuration file.

Fortunately, it is set separately or it can't be used. Can you tell me why it can't load the setting interface? I communicate with edxp developers.

**Comment by Didgeridoohan** [comment] 2019-03-22 14:56
I actually took another quick look at the logs to refresh my memory, and found something interesting...

With EdXposed active the boot order on your device is completely broken.  Late_start service happens before module construction and mounting of files. That's why things aren't working. It has nothing to do with this module...

**Comment by 2220209876** [comment] 2019-03-23 03:48
> I actually took another quick look at the logs to refresh my memory, and found something interesting...
> 
> With EdXposed active the boot order on your device is completely broken. Late_start service happens before module construction and mounting of files. That's why things aren't working. It has nothing to do with this module...

How to deal with it? 'Late_start' status of 'MagiskHidePropsConf' has not been set before.

**Comment by Didgeridoohan** [comment] 2019-03-23 06:48
How to deal with it? The developer of EdXposed needs to make sure that the mod doesn't break Magisk...
