### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Orel6505** [Magisk-Modules-Repo/MagiskHidePropsConf#112] opened 2021-09-04 12:47 UTC
Hey, in the latest release (6.0.0). after unlocking the lock screen after reboot, the phone entering back to bootanim and returns to lock screen, this not happening twice.

**Comment by Orel6505** [comment] 2021-09-04 12:49
Rom - crDroid 7.9 
Phone - Beyond1lte (Samsung Galaxy S10)
Props I used (redfin - pixel 5 props)

**Comment by Didgeridoohan** [comment] 2021-09-04 14:21
As always, logs will be necessary:
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs

**Comment by vista0815** [comment] 2021-09-04 16:09
Have recognized the same issue

**Comment by Didgeridoohan** [comment] 2021-09-04 16:44
> Have recognized the same issue

If there are issues, the aforementioned logs would be needed to properly troubleshoot.

**Comment by Orel6505** [comment] 2021-09-04 17:11
I will take logs tomorrow.

**Comment by gordboy** [comment] 2021-09-04 18:40
I have the same issue with Release 6.0.0. Device reboots once after power on or reboot, and then is fine.

Oneplus 8T running LOS 18.1, with one other active Magisk Module - Systemless Hosts

Gone back to previous version for now..

**Comment by Didgeridoohan** [comment] 2021-09-05 07:33
Should be fixed in f12cd6e722e963a97776eaf4ef2e93c444f4f5bf

For some background: it's actually not a bug, but a feature... :smile: In some instances it is necessary to do a soft reboot at the end of the boot process, for the props to be propely set to memory. But, since some (mainly Samsung it seems) users experienced weird issues I've made this an option instead. See the docs for more details.

**Closed by Didgeridoohan** 2021-09-05 07:33 UTC

**Comment by gordboy** [comment] 2021-09-05 13:49
Fixed in 6.0.1. Thanks for your diligent hard work.
