### ISSUE TITLE
util_functions.sh: No such file or directory

### ISSUE THREAD

**Issue by AlperSal** [Magisk-Modules-Repo/MagiskHidePropsConf#95] opened 2021-04-19 06:37 UTC
As you can see in the picture;
![image](https://user-images.githubusercontent.com/34231577/115191717-7c210280-a0f2-11eb-90bc-4cbd0a308423.png)
I am getting that error. I tested in Termux with su, this error. Tested in ADB shell (photo), same error. How can I fix that?

Edit: Root granted in both of them.

**Comment by Didgeridoohan** [comment] 2021-04-19 17:35
Some kind of broken installation, perhaps...

Can't say much without logs.
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#collecting-logs-manually

**Comment by Didgeridoohan** [comment] 2021-04-20 06:18
From the looks of it you've got problems with the cp and sed commands (at the least). No idea why it can't find the util_functions script. It's clearly in place, judging by the logs...

I cannot reproduce anything of what you're seeing, and I can't see any apparent reason as to why you would have those issues. Perhaps it has to do with this:
https://github.com/topjohnwu/Magisk/issues/4225

You could try uninstalling the module and installing it again. Another couple of things to try would be installing the Magisk Canary release to see if that changes anything, or maybe try downgrading to Magisk v22.0 since that seems to help with the issues that can be seen in the linked issue ticket above.

**Comment by AlperSal** [comment] 2021-04-20 06:30
Thanks for reply. I tried reinstalling 5 hours ago. (Bec. you said could be broken installation) but same error. I'm in a beta testing of a kernel so I will try Magisk downgrading or upgrading about 20 days later when the stable release releases. Thanks for replying again. Have a nice day.

**Comment by Didgeridoohan** [comment] 2021-05-13 10:13
Any news? Does Magisk v23 fix the issue (there are busybox fixes in there)?

**Comment by AlperSal** [comment] 2021-05-13 10:48
Updating to Magisk v23 didn't fix the problem. Later I asked the dev of my kernel and rom for help and he made it work. If you want to see the steps I can send you the Discord server's link. (As mail or directly here, you choose) (Also he is not sure is the problem's reason is magisk or module)

**Comment by Didgeridoohan** [comment] 2021-05-13 10:51
Sure, that would be interesting. If you don't want to post the link here, my mail is in my bio.

**Comment by AlperSal** [comment] 2021-05-13 10:58
Okey, check your mail.

**Comment by Didgeridoohan** [comment] 2021-05-13 11:28
So, It's a permissions thing. But the module installation script should be taking care of setting all the required permissions.

If you could help me with a test, it would be great if you could uninstall and then install the module again now that you are on Magisk v23. If that works we know that it likely was the now fixed busybox issue that was the culprit.

**Comment by AlperSal** [comment] 2021-05-13 11:32
Okey say me what to do, I would like to help.

**Comment by Didgeridoohan** [comment] 2021-05-13 11:37
To be sure that the stuff you guys did to get it to work down not interfere, I would need you to uninstall the module (nothing else) before installing it again. If you are on Magisk v23 everything should in theory work as expected after that. This test would confirm the theory...

**Comment by AlperSal** [comment] 2021-05-13 11:37
Uninstalled, rebooted, installed, rebooted, > su    > props     >Works fine

**Comment by AlperSal** [comment] 2021-05-13 11:39
I think I can close the issue. (Also can you check Discord? I really can't understand what to do for enabling device simulation)

**Comment by Didgeridoohan** [comment] 2021-05-13 11:40
Excellent. Mystery solved... Thank you very much for the help in figuring things out.

I need to get some school work done, but I'll take a closer look at your simulation issues when I get a moment.

**Closed by Didgeridoohan** 2021-05-13 11:40 UTC

**Comment by Didgeridoohan** [comment] 2021-05-13 18:46
@AlperSal If you've used the module to set a device fingerprint, then the "Device simulation" option should become available (you don't even have to reboot first).

If you've set a device fingerprint but still can't enter the "Device simulation" menu (number 2 in the main menu) there is something wrong, yes. But if you can enter the menu (there's no "Disabled" text next to the option in the main menu) you should just be able to enable simulation by selecting "s" and then (once you're done enabling simulation) picking what props you want to simluate.

I've deliberately made it cumbersome to enable this feature since it has the potential to cause issues... 

Could you give more details as to what you see on your device?

**Comment by AlperSal** [comment] 2021-05-13 19:28
Here is a video representing what did I do in general.
https://drive.google.com/file/d/18IMGH44pSCIC7Zp67kxq-LW9xwiwtW4T/view?usp=drivesdk

**Comment by Didgeridoohan** [comment] 2021-05-13 19:34
I'd need logs to have a chance to figure it out...

**Comment by AlperSal** [comment] 2021-05-13 19:40
Here logcat's: https://drive.google.com/file/d/18Xrrwi2CxIxZPdaOzMPJ1OQqTCf3HOIH/view?usp=drivesdk
Here props's:  https://drive.google.com/file/d/18YosmIq4D3sDNcm1P8Wyx_UIgjotal4K/view?usp=drivesdk

**Comment by Didgeridoohan** [comment] 2021-05-13 20:37
You've been messing with the Magisk internals... Even though osm0sis' busybox should be the same as the one John is using, that's definitely a possible source of errors. A clean installation (or at least a reinstall) of Magisk might be in order.

Besides that there are clear problems with the sed command (still) and as such no options are actually changed when you pick a fingerprint. The command is just killed off and I have no idea why. Maybe because you've been tinkering with the internals, but I doubt it. Could be something about your ROM, or something else.

What happens if you run `su -c /data/adb/magisk/busybox sed` in your terminal app?

**Comment by AlperSal** [comment] 2021-05-13 20:46
```
BusyBox v1.33.1-osm0sis (2021-05-06 01:25:17 ADT) multi-call binary.

Usage: sed [-i[SFX]] [-nrE] [-f FILE]... [-e CMD]... [FILE]...
or: sed [-i[SFX]] [-nrE] CMD [FILE]...

        -e CMD  Add CMD to sed commands to be executed
        -f FILE Add FILE contents to sed commands to be executed                                                        -i[SFX] Edit files in-place (otherwise sends to stdout)
                Optionally back files up, appending SFX         -n      Suppress automatic printing of pattern space
        -r,-E   Use extended regex syntax

If no -e or -f, the first non-option argument is the sed command string.
Remaining arguments are input files (stdin if none).
```

This is the result of the command.

**Comment by AlperSal** [comment] 2021-05-13 20:50
I will try reinstalling Magisk then.

**Comment by AlperSal** [comment] 2021-05-13 21:51
Deleted /data/adb/magisk/ and redownloaded via Magisk app. This works like a charm! Thanks for help!
