### ISSUE TITLE
CTS profile still fails on magisk 24.3

### ISSUE THREAD

**Issue by Relected** [Magisk-Modules-Repo/MagiskHidePropsConf#140] opened 2022-03-18 09:46 UTC
I have tried all methods I could to pass CTS, but I still couldn't. Currently using the treble gsi option 

Those are my log files 

[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/8303392/propslogs.tar.gz)

I hope I get to pass CTS for my apps to work properly

**Comment by Didgeridoohan** [comment] 2022-03-22 20:20
What if you don't use the treble gsi print and instead pick one from the list?

**Comment by Relected** [comment] 2022-03-23 03:44
@Didgeridoohan still doesn't work too, same results

**Comment by Didgeridoohan** [comment] 2022-03-24 14:51
Another "doesn't work" without any logs... Pro tip: when possible, always include logs.

**Comment by Relected** [comment] 2022-03-25 06:34
@Didgeridoohan I'm pretty sure I sent logs alongside this issue

**Comment by Didgeridoohan** [comment] 2022-03-25 06:43
Yes, in your first post and the original issue... But then you tried something new and when that didn't work either you need to send new logs showing the new setup. I can't guess at what's going on, I need to see logs for the stuff you are doing that doesn't work.

**Comment by Relected** [comment] 2022-03-25 08:31
@Didgeridoohan these logs are for what is currently MHPC running on my system

**Comment by Didgeridoohan** [comment] 2022-03-25 08:40
Which logs? Did you forget to upload? The only logs in this issue are the ones attached to the first post. They only show the setup where you use the GSI option. I would need to see the logs showing you using a fingerprint from the included prints list as well...

**Comment by Relected** [comment] 2022-03-25 09:18
@Didgeridoohan this is when I tried using the p20 lite's fingerpring
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/8349103/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment] 2022-03-25 09:54
Everything looks fine in those logs and the module is working as intended. Here's what I'm thinking:
- There's something about your setup preventing you from passing SafetyNet (wrong settings, ROM, apps, mods, etc).
- The bootloader unlocked hiding methods need updating.
- The method to change device fingerprint doesn't work anymore (although I doubt that'll stop working before Google changes the SafetyNet API, and by that time it's likely game over anyway).

I'm gonna close this since the module is working exactly as intended. If you ever find out that whatever was causing your issue can be fixed by an update to this module please reopen this issue or open a new one.

**Closed by Didgeridoohan** 2022-03-25 09:54 UTC
