### ISSUE TITLE
bug:set ro.debuggable success,but ddms do not show all processes

### ISSUE THREAD

**Issue by fishso** [Magisk-Modules-Repo/MagiskHidePropsConf#46] opened 2020-02-13 13:47 UTC
phone: pixel\nexus 6p
android os : 8.1
magisk: 20.3
MagiskHidePropsConf: v5.1.2
Edxposed: v0.4.5.1（YAHFA）
Riru-core:V19.6
magisk hide is `off`.

I used `props` change  `ro.debuggable=1` and `ro.secure=0`, then reboot device,execute command 
 in adb shell `getprop ro.debuggable`,the value show is `1`,but the ddms  show the processes as fallow:
![process](https://user-images.githubusercontent.com/10240813/74440527-1eb77300-4ea9-11ea-8359-19a8759c4aa8.png)

but use the command 
```
adb shell
su
magisk resetprop ro.debuggable 1
stop;start; 
```
the ddms show process as fallow:
![mag](https://user-images.githubusercontent.com/10240813/74440945-e7959180-4ea9-11ea-9d49-134bbf27b57e.png)

props set ro.debuggable is success, but ddms do not show all processes, is it a bug?

**Comment by Didgeridoohan** [comment] 2020-02-13 17:17
Not sure what that could be about...

Are you using the "Edit MagiskHide props" option or "Add/edit custom props"?

**Comment by fishso** [comment] 2020-02-14 12:44
> Not sure what that could be about...
> 
> Are you using the "Edit MagiskHide props" option or "Add/edit custom props"?

 I am using the "Edit MagiskHide props"

**Comment by Didgeridoohan** [comment] 2020-02-14 20:35
Could you run a few tests for me?

1. Edit /data/adb/modules/MagiskHidePropsConf/service.sh line 105 and remove the n from `resetprop -nv`. Then reboot and see if there's any difference.
2. Use the "Add/edit custom props" option instead, and test all three boot stages one by one and let me know if any of them work as expected.

**Comment by fishso** [comment] 2020-02-17 13:30
> Could you run a few tests for me?
> 
> 1. Edit /data/adb/modules/MagiskHidePropsConf/service.sh line 105 and remove the n from `resetprop -nv`. Then reboot and see if there's any difference.
> 2. Use the "Add/edit custom props" option instead, and test all three boot stages one by one and let me know if any of them work as expected.

Success. I do as  fallow:
1. change `service.sh` line 102 `resetprop -nv` to  `resetprop -v` ,reboot but no difference.
2.reset `MagiskHide props` ,Use the "Add/edit custom props" option instead, add `ro.debuggable=1`,then select `4 - both boot stages (current)`,then reboot and I find DDMS show all processes.
3. change `service.sh` line 102 `resetprop -v` to  `resetprop -nv` ,reboot  but no difference.
so, Use the `Add/edit custom props` is success, `resetprop -v` or `resetprop -nv`  seems no difference.

thanks a lot.

**Comment by Didgeridoohan** [comment] 2020-02-17 14:33
> Success. I do as fallow:
> 
> 1. change `service.sh` line 102 `resetprop -nv` to  `resetprop -v` ,reboot but no difference.
> 2. reset `MagiskHide props` ,Use the "Add/edit custom props" option instead, add `ro.debuggable=1`,then select `4 - both boot stages (current)`,then reboot and I find DDMS show all processes.
> 3. change `service.sh` line 102 `resetprop -v` to  `resetprop -nv` ,reboot  but no difference.
>    so, Use the `Add/edit custom props` is success, `resetprop -v` or `resetprop -nv`  seems no difference.
> 
> thanks a lot.

Could you test what happens if you use the custom prop option and set boot stage to late_start service?

**Comment by fishso** [comment] 2020-02-18 15:49
use the custom prop option,boot stage test : 
1.set  `late_start service`,ddms show no process.
2.set  `post-fs-data`,ddms show all processes.
3.set  `default`,ddms show no processes.

by the way , reboot devices and execute `props` show error:
```
 The service.sh module script does not
 appear to have run during boot.

 This means the module won't work.

 Please reboot your device and see if
 it does run.

 Things to try:
 Disable EdXposed.
 Change boot stage settings or background
 execution for the boot script
 (run the props
 command with the -s option).

 If the issue persists after a reboot,
 please report the issue, with logs!

 Logs have automatically been saved
 to your internal storage
 (propslogs.tar.gz).

 If the automatic collection failed,
 please collect the logs manually.
```
the log file :
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/4220102/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment] 2020-02-18 16:18
Ok, thank you for testing. I might add a `stop;start;` to the "Edit MagiskHide props" function...

The service.sh script doesn't finish and that's why you're seeing that error. Possibly caused by EdXposed.

**Comment by Didgeridoohan** [comment] 2020-02-26 21:30
Probably fixed in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/13a72e0f9603f42372341d8162159762cec68d40

**Closed by Didgeridoohan** 2020-02-26 21:30 UTC
