### ISSUE TITLE
The post-fs-data.sh module script does not  appear to have run during boot

### ISSUE THREAD

**Issue by papastar** [Magisk-Modules-Repo/MagiskHidePropsConf#41] opened 2019-12-05 11:14 UTC
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3926518/propslogs.tar.gz)

The post-fs-data.sh module script does not
 appear to have run during boot.

 This means the module won't work.

 Please reboot your device and see if
 it does run.

 Things to try:
 Disable EdXposed.
 Change boot stage settings or background
 execution for the boot script
 (run the props
 command with the -s option).

 If the issue persists after a reboot,
 please report the issue, with logs!

 Logs have automatically been saved
 to your internal storage
 (propslogs.tar.gz).

 If the automatic collection failed,
 please collect the logs manually.

 See the documentation for further details.

log have upload
thank you !

**Comment by Didgeridoohan** [comment] 2019-12-05 11:46
Most likely caused by EdXposed. Did you try as the error message suggests, and disable EdXposed to see if that fixes things? If not, do that...

Take a look at the docs for more info:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#known-issues

From what I can see it's not a module issue. Closing.

**Closed by Didgeridoohan** 2019-12-05 11:46 UTC
