### ISSUE TITLE
Sed not working on prop names?

### ISSUE THREAD

**Issue by timeakesmarky** [Magisk-Modules-Repo/MagiskHidePropsConf#33] opened 2019-07-29 02:02 UTC
Can you please add support to change values in default.prop?
I need to change some values. I used resetprop and I have to do this on each reboot.

Thanks!

**Comment by Didgeridoohan** [comment] 2019-07-29 06:57
Any prop that is found in default.prop (or anywhere else for that matter) can already be changed with the module.

**Comment by timeakesmarky** [comment] 2019-07-29 17:52
Thanks, how do I do this? I couldn't understand from the documentation. :)

**Comment by Didgeridoohan** [comment] 2019-07-29 18:03
Run the props command and pick the "Add/edit custom props" option. After that it's just a matter of following the on screen instructions.

**Comment by timeakesmarky** [comment] 2019-07-29 18:24
I tried this but it says no custom props set and asks me to add a new prop. I wish it could just list the props (like resetprop) and I could change it.

I used resetprop to change some values. I want these values to persist after reboot, so I installed this module.

**Comment by Didgeridoohan** [comment] 2019-07-29 18:55
Yes, you do need to know what prop it is that you want to change. Enter the prop and then the value you want to set it to.

If you don't want to use the module you can just create a boot script with your resetprop commands.

**Comment by timeakesmarky** [comment] 2019-07-29 18:57
I added a new prop with the same name as the one I wanted to change and it asked me set the value, I set it and typed "y" to continue and the cursor moves to the next line and nothing happens. It gets stuck there.

I want to use it, I just want it to work.
I don't know how to create a boot script.

**Comment by Didgeridoohan** [comment] 2019-07-29 19:05
Get me the module logs and I might be able to help:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#logs

**Comment by timeakesmarky** [comment] 2019-07-29 20:41
[propsconf.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3444205/propsconf.log)
Logs...

**Comment by Didgeridoohan** [comment] 2019-07-29 20:50
Doesn't show anything, unfortunately. Could you screenshot and post your process, so I can see what's happening in the terminal output.

**Comment by timeakesmarky** [comment] 2019-07-29 20:53
![Screenshot_2019-07-30-02-22-20-713_com termux](https://user-images.githubusercontent.com/7058205/62081798-01a2b600-b271-11e9-838c-4dc53fc5ac4f.png)

**Comment by Didgeridoohan** [comment] 2019-07-29 21:05
I have no clue what that could be about. Something is really broken and I can't reproduce it on my end. I'll investigate further tomorrow.

Meanwhile, could you post your propsconf.log, propsconf_last.log and Magisk log and I'll take a look at those when I can.

**Comment by timeakesmarky** [comment] 2019-07-29 21:12
propsconf_last.log is the same as the log I posted before because I'm doing the same thing again and again. I don't have any magisk modules. This is the only module.
I installed busybox from osmosis but it didn't fix the issue.

[magisk.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3444289/magisk.log)

**Comment by Didgeridoohan** [comment] 2019-07-30 05:20
Still, it would have been good to see them both and compare a few things (even if they would have shown the same things). Thinking about it, the install log (both from Magisk and the module) would also have been nice to see...

Anyway, for the moment I have no idea why things are failing (I know how, but not why). You could try simply uninstalling and installing the module again, to see if something got messed up along the way. If you do, make sure to save the install log from the Manager as well, in case things still don't work.

What device is this, by the way?

**Comment by timeakesmarky** [comment] 2019-07-31 06:03
[magisk.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3450061/magisk.log)
[propsconf.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3450062/propsconf.log)
[propsconf_last.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3450063/propsconf_last.log)

I'm using a Nexus 5 running MIUI. Actually, it was a fresh install.

**Comment by Didgeridoohan** [comment] 2019-07-31 06:44
Unfortunately I have very little to go on with this... Like I said, I think I see what is happening but I have no idea why. I could whip up a script to check more thoroughly what's going on at boot, but that would take some time that I currently don't have much of... I will revisit this as soon as possible.

My current guess and gut feeling is that it is something about MIUI that is causing issues. Wouldn't be the first time...

**Comment by Didgeridoohan** [comment] 2019-08-03 05:43
Reopening this so I don't forget about it.

**Comment by Didgeridoohan** [comment] 2019-11-02 22:55
Hopefully the v5.0.0 release should take care of at least some of the issues here.

**Comment by Didgeridoohan** [comment] 2019-11-04 10:14
Reopening to keep track of an issue with sed seemingly not truncating the prop names properly. Multiple reports in the support thread.

**Comment by Didgeridoohan** [comment] 2019-11-22 19:32
Should finally be fixed in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/37d57ad3bbf750245888c9536d0609c4efdca12d

**Closed by Didgeridoohan** 2019-11-22 19:32 UTC
